[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "ucs503p-202627-memorylane"
version = "0.0.1"
authors = [
  { name="Rabeeh Ahmad", email="your-email@example.com" },
]

description = "MemoryLane - UCS503 Software Engineering Project"
readme = "README.md"
requires-python = ">=3.8"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: POSIX",
    "Programming Language :: Unix Shell",
]

dependencies = [
    "click"
]

[project.urls]
Homepage = "https://github.com/rabeeh18/ucs503p-202627-MemoryLane"
Issues = "https://github.com/rabeeh18/ucs503p-202627-MemoryLane/issues"

# Pytest configuration
[tool.pytest.ini_options]
pythonpath = [
  "code"
]